### ISSUE TITLE
Variable number of columns

### ISSUE THREAD

**Issue by digitalbase** [iRessources/AgileDwarf#17]
First of all thanks for your great project. Looking good !

In our (scrum) development proces we are using more then 3 stages for issues. We use :
- unassigned / new
- assigned
- completed
- tested
- accepted

The current version of the plugin contains 3 fixed columns. I would suggest making the number of columns variable, to be defined in the project settings screen.

After that one should have the ability to set the status per column.

**Comment by markablov** [comment]
Done. 5e201db35e672df818e63fa5b2bf70233542a843
Columns are too wide to place it 4-5 in one row, that's why there is second row.

**Comment by lfagundes** [comment]
This commit made my tasks screen blank, it's worth noticing that the configuration is general and not per-project.

The behavior is weird, because the 2 columns that were configured didn't appear until I changed the configuration to 3 columns, than everything worked fine.

**Comment by digitalbase** [comment]
Thanks for that ! You are fast ! Makes the whole plugin a lot more flexible.
