### ISSUE TITLE
Json.encode() problem

### ISSUE THREAD

**Issue by yuters** [iRessources/AgileDwarf#2]
Hi, 

I'm really looking forward to use this.

Maybe it's something about my setup but...

https://github.com/iRessources/AgileDwarf/blob/master/app/views/adtasks/list.html.erb#L21
https://github.com/iRessources/AgileDwarf/blob/master/app/views/adsprints/list.html.erb#L21

I get this:

```
{&quot;4&quot;:&quot;yuters&quot;}
```

Do you know what could cause this?

**Comment by markablov** [comment]
Thanks, pull request merged.
