### ISSUE TITLE
Update to 4d1464

### ISSUE THREAD

**Issue by digitalbase** [iRessources/AgileDwarf#20]
Last version in git 4d14649f770d6b3eef44e595c678484e435c51a5
If i go to https://development.digitalbase.eu/adsprints/list?project_id=PROJECTNAME i get error. Production.log gives following :

Processing AdsprintsController#list (for 81.82.199.46 at 2012-08-14 23:59:55) [GET]
 Parameters: {"project_id"=>"prezly", "action"=>"list", "controller"=>"adsprints"}
Rendering template within layouts/base
Rendering adsprints/list

ActionView::TemplateError (No route matches {:action=>"7078", :controller=>"issues"}) on line #2 of vendor/plugins/AgileDwarf/app/views/adsprints/_task.html.erb:
1: <div id="task.<%=h task.id %>" class="sc_task <%= @closed_status == task.status_id ? 'closed_task' : '' %>">
2:   <div class="fl task_no"><a href="<%= url_for(:controller => 'issues', :action => task.id) %>">#<%=h task.id %></a></div>
3:   <div class="fl task_desc"><img src="<%= File.join(@plugin_path, 'images', 'task_desc.png') %>"/></div>
4:   <div class="task_subject"><%=h task.subject %></div>
5:   <div class="task_estimate fl"><%=h task.estimated_hours || l(:label_sprints_placeholder_estimated) %></div>

```
vendor/plugins/AgileDwarf/app/views/adsprints/_task.html.erb:2
vendor/plugins/AgileDwarf/app/views/adsprints/list.html.erb:72
```

**Comment by digitalbase** [comment]
Also rake redmine:plugins:migrate didn't work :

Please install RDoc 2.4.2+ to generate documentation.
rake aborted!
Don't know how to build task 'redmine:plugins:migrate'

rake db:migrate_plugins actually did.

I am on redmine 1.4-stable

URL: http://redmine.rubyforge.org/svn/branches/1.4-stable
Repository Root: http://redmine.rubyforge.org/svn
Repository UUID: e93f8b46-1217-0410-a6f0-8f06a7374b81
Revision: 10207

**Comment by markablov** [comment]
Fixed, 0173261
thanks to https://github.com/zashme

**Comment by digitalbase** [comment]
Thanks. You rock.

**Comment by digitalbase** [comment]
rocessing AdtasksController#list (for 213.181.51.50 at 2012-08-16 11:47:41) [GET]
  Parameters: {"action"=>"list", "project_id"=>"prezly", "controller"=>"adtasks"}
Rendering template within layouts/base
Rendering adtasks/list

ActionView::TemplateError (No route matches {:action=>"6794", :controller=>"issues"}) on line #2 of vendor/plugins/AgileDwarf/app/views/adtasks/_task.html.erb:
1: <div id="task.<%=h task.id %>" class="sc_task">
2:   <div class="fl task_no"><a href="<%= url_for(:controller => 'issues', :action => task.id) %>">#<%=h task.id %></a></div>
3:   <div class="fl task_desc"><img src="<%= File.join(@plugin_path, 'images', 'task_desc.png') %>"/></div>
4:   <div class="task_subject" title="<%=h task.subject %>"><%=h task.subject %></div>
5:   <div class="task_row">

**Comment by digitalbase** [comment]
i am on 0173261 now. Doesn't work

ctionView::TemplateError (No route matches {:action=>"6794", :controller=>"issues"}) on line #2 of vendor/plugins/AgileDwarf/app/views/adtasks/_task.html.erb:
1: <div id="task.<%=h task.id %>" class="sc_task">
2:   <div class="fl task_no"><a href="<%= url_for(:controller => 'issues', :action => task.id) %>">#<%=h task.id %></a></div>
3:   <div class="fl task_desc"><img src="<%= File.join(@plugin_path, 'images', 'task_desc.png') %>"/></div>
4:   <div class="task_subject" title="<%=h task.subject %>"><%=h task.subject %></div>
5:   <div class="task_row">

```
vendor/plugins/AgileDwarf/app/views/adtasks/_task.html.erb:2
vendor/plugins/AgileDwarf/app/views/adtasks/_column.html.erb:4
vendor/plugins/AgileDwarf/app/views/adtasks/list.html.erb:65
passenger (3.0.15) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.15) lib/phusion_passenger/utils.rb:470:in `safe_fork'
passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.15) helper-scripts/passenger-spawn-server:99
```

**Comment by markablov** [comment]
d24f53544909be7c478facb7c54f68f470e82d85

**Comment by digitalbase** [comment]
works !
