### ISSUE TITLE
Sprint page

### ISSUE THREAD

**Issue by yquenechdu** [iRessources/AgileDwarf#23]
I tested AgileDwarf with a fresh version of redmine (2.0.3)
Ruby 1.9.3 and rails 3.2.6

But, when I click on Sprint tab, I have this error message :
"Page not found
The page you were trying to access doesn't exist or has been removed."

The log result

ActionController::RoutingError (No route matches {:controller=>"issues", :action=>"2"}):
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:532:in `raise_routing_error'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:528:in`rescue in generate'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:520:in `generate'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:561:in`generate'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:586:in `url_for'
  actionpack (3.2.6) lib/action_dispatch/routing/url_for.rb:148:in`url_for'
  actionpack (3.2.6) lib/action_view/helpers/url_helper.rb:107:in `url_for'
  plugins/AgileDwarf/app/views/adsprints/_task.html.erb:2:in`_plugins__gile_warf_app_views_adsprints__task_html_erb__3518506150490167106_46058260'
  actionpack (3.2.6) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.6) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.6) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:351:in`block in collection_with_template'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:348:in `each'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:348:in`collection_with_template'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:250:in `render_collection'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:234:in`block in render'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.6) lib/action_view/renderer/partial_renderer.rb:233:in`render'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:15:in`render'
  actionpack (3.2.6) lib/action_view/helpers/rendering_helper.rb:24:in `render'
  prototype-rails (3.2.1) lib/prototype-rails/rendering.rb:8:in`render_with_update'
  plugins/AgileDwarf/app/views/adsprints/list.html.erb:72:in `_plugins__gile_warf_app_views_adsprints_list_html_erb__4611234015237612538_47004020'
  actionpack (3.2.6) lib/action_view/template.rb:145:in`block in render'
  activesupport (3.2.6) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.6) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:18:in`render'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:17:in`render'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.6) lib/action_controller/metal/streaming.rb:225:in`_render_template'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/renderers.rb:28:in`render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:88:in`render'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/benchmark.rb:295:in`realtime'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in`block in render'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__1683957725107218098__process_action__1624131163023742839__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in`process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__1482319334800148788__call__2257677014715223011__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.6) lib/rails/engine.rb:479:in`call'
  railties (3.2.6) lib/rails/application.rb:220:in `call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in`method_missing'
  passenger (3.0.15) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:516:in`accept_and_process_next_request'
  passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in`start_request_handler'
  passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/utils.rb:470:in`safe_fork'
  passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:180:in`start'
  passenger (3.0.15) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:219:in`block (2 levels) in spawn_rails_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:214:in`block in spawn_rails_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in`synchronize'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:213:in`spawn_rails_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.15) helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by jscorrea** [comment]
Same error here

**Comment by TheRedBull** [comment]
Same here

**Comment by markablov** [comment]
Fixed, 0173261
thanks to https://github.com/zashme

**Comment by digitalbase** [comment]
i don't know if it is fixed. I am on 0173261.

Still same on Sprint & Task pages.

rocessing AdtasksController#list (for 213.181.51.50 at 2012-08-16 11:47:41) [GET]
  Parameters: {"action"=>"list", "project_id"=>"prezly", "controller"=>"adtasks"}
Rendering template within layouts/base
Rendering adtasks/list

ActionView::TemplateError (No route matches {:action=>"6794", :controller=>"issues"}) on line #2 of vendor/plugins/AgileDwarf/app/views/adtasks/_task.html.erb:
1: <div id="task.<%=h task.id %>" class="sc_task">
2:   <div class="fl task_no"><a href="<%= url_for(:controller => 'issues', :action => task.id) %>">#<%=h task.id %></a></div>
3:   <div class="fl task_desc"><img src="<%= File.join(@plugin_path, 'images', 'task_desc.png') %>"/></div>
4:   <div class="task_subject" title="<%=h task.subject %>"><%=h task.subject %></div>
5:   <div class="task_row">

```
vendor/plugins/AgileDwarf/app/views/adtasks/_task.html.erb:2
vendor/plugins/AgileDwarf/app/views/adtasks/_column.html.erb:4
vendor/plugins/AgileDwarf/app/views/adtasks/list.html.erb:65
```

**Comment by markablov** [comment]
d24f53544909be7c478facb7c54f68f470e82d85

**Comment by digitalbase** [comment]
works ! thanks !

**Comment by TheRedBull** [comment]
Working for me as well; thank you for the quick fix!

**Comment by yquenechdu** [comment]
Thank for you fix.
