### ISSUE TITLE
Javascript errors when viewing tasks or sprints

### ISSUE THREAD

**Issue by stefan-h-singer** [iRessources/AgileDwarf#31]
Uncaught TypeError: Object [object Object] has no method 'attachEvent' prototype.js:5644
observe prototype.js:5644
_methodized prototype.js:438
(anonymous function) list:455

Uncaught TypeError: Object [object Object] has no method 'dispatchEvent' prototype.js:5734
fire prototype.js:5734
_methodized prototype.js:438
fireContentLoadedEvent prototype.js:5820

Uncaught TypeError: Object [object Object] has no method 'attachEvent' prototype.js:5653
observe prototype.js:5653
_methodized prototype.js:438
Class.create.submitAction application.js:481
(anonymous function) prototype.js:391
(anonymous function) prototype.js:825
each prototype.js:824
Class.create.initialize application.js:457
klass prototype.js:101
(anonymous function) list:22
responder

**Comment by markablov** [comment]
Fixed. 57bd56b7bf37ee6ca27e2e1a8fe7994da9222c0c

**Comment by stefan-h-singer** [comment]
Indeed! Thanks.
