### ISSUE TITLE
Sprints from sub projects

### ISSUE THREAD

**Issue by GreenRover** [iRessources/AgileDwarf#32]
Hy, first a big thank you for your great work.

I have a project with some sub projects.
For my version i choose to share them with all sub-projects.

Now i have the problem:
When i view the "Sprints" overview for the main project, i wont see there the task from the sub projects.
When i view the "Sprints" overview for a sub project i wont see the Sprint/Version which was pass from the/shared with the main project.

Friendly regards
Heiko

**Comment by spaluc** [comment]
+1

**Comment by mormeldier** [comment]
I agree. Our subprojects should all follow the same sprint planning as the main project.

**Comment by GreenRover** [comment]
Very out dated
