### ISSUE TITLE
"Resolved" task board not appearing

### ISSUE THREAD

**Issue by oidoug** [iRessources/AgileDwarf#57]
The Resolved board that should appear on the Tasks panel is missing on my installation.
Maybe it's just a configuration issue, and I'll be very glad if anyone could help me go through this.
Or it could be a bug. I got (and resolved) the issue #34 and this might be something similar.

No error is reported on the console when I open the Tasks panel. I'm also sending a screenshot to demonstrate the issue.
I'm using redmine 1.3.2.stable (MySQL).

Thank you so much for your help!

![Screen Shot 2013-02-14 at 3 44 06 PM](https://f.cloud.github.com/assets/129619/160576/fc3fe4d2-776a-11e2-9cb5-bdd5e42fb63f.png)

**Comment by AlexAndrascu** [comment]
Go to settings/plugin/AgileDwarf and select the desired Number of columns. Then underneath set the Task Status of each column so in your case 1st New 2nd In Progress 3rd Resolved

**Comment by oidoug** [comment]
Ha, felling dumb now :)
Thanks Alex!

**Comment by ghost** [comment]
maximum number of columns is 5, how & where we can increase that?
as you know kanban board has more columns!
