### ISSUE TITLE
Postgres Error on Run Charts

### ISSUE THREAD

**Issue by robo-cbtn** [iRessources/AgileDwarf#69]
Using redmine 2.3 and postgres 9.1 I get this error when clicking the Run Charts tab.

Started GET "/adburndown/show?project_id=nuggets" for 172.16.1.78 at Fri May 24 08:54:58 -0700 2013
Processing by AdburndownController#show as HTML
  Parameters: {"project_id"=>"nuggets"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 38ms

ActiveRecord::StatementInvalid (PGError: ERROR:  syntax error at or near "`"
LINE 1: ...op_key, DATE(journals.created_on) created_on from`journals`...
                                                             ^
: select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from`journals`inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and project_id = 1 order by journals.id desc) a group by`issueId`, created_on, prop_key order by created_on desc):
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/postgresql_adapter.rb:1160:in`async_exec'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/postgresql_adapter.rb:1160:in `exec_no_cache'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/postgresql_adapter.rb:659:in`exec_query'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/postgresql_adapter.rb:658:in`exec_query'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/postgresql_adapter.rb:1255:in `select'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/database_statements.rb:18:in`select_all'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/query_cache.rb:75:in`cache_sql'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
  plugins/AgileDwarf/app/controllers/adburndown_controller.rb:57:in`show'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:4:in `send_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:4:in`send_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:167:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:10:in`process_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:18:in `process_action'
  activesupport (3.2.13) lib/active_support/callbacks.rb:480:in`_run__6437172__process_action__974005348__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:17:in`process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:30:in`process_action'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:29:in`process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:18:in`process_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:121:in `process'
  /usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:45:in`process'
  /usr/lib/ruby/vendor_ruby/action_controller/metal.rb:203:in `dispatch'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  /usr/lib/ruby/vendor_ruby/action_controller/metal.rb:246:in `action'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:73:in`call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:36:in`call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:68:in `call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in`each'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:612:in`call'
  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  /usr/lib/ruby/vendor_ruby/rack/etag.rb:23:in `call'
  /usr/lib/ruby/vendor_ruby/rack/conditionalget.rb:25:in`call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/head.rb:14:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/params_parser.rb:21:in`call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/flash.rb:242:in`call'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:205:in `context'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:200:in`call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/cookies.rb:341:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:64:in`call'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:28:in`call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__207265953__call__4__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`send'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in`run_callbacks'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:31:in`call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:32:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:16:in`call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:16:in`call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:21:in`call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  /usr/lib/ruby/vendor_ruby/rack/lock.rb:15:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:63:in`call'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:136:in `forward'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:245:in`fetch'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:185:in `lookup'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:66:in`call!'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:51:in `call'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:479:in`call'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:223:in `call'
  /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in`send'
  /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb:275:in`send'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:479:in`safe_fork'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in`__send__'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:82:in`synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:213:in`spawn_rails_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in `__send__'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99

**Comment by exocode** [comment]
same here...

**Comment by ovidiuvisan** [comment]
Same problem.

**Comment by eximius313** [comment]
Its simple - just apply this patch

```
--- adburndown_controller.rb.orig
+++ adburndown_controller.rb
@@ -54,11 +54,11 @@ class AdburndownController < ApplicationController
     @changes = []
     # restcondchanges = ActiveRecord::Base::sanitize_sql(restcondtasks)
     restcondchanges = ActiveRecord::Base.send(:sanitize_sql, restcondtasks, '')
-    ActiveRecord::Base.connection.select_all("select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from `journals` inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and #{restcondchanges} order by journals.id desc) a group by `issueId`, created_on, prop_key order by created_on desc").each{|row| @changes << row}
+    ActiveRecord::Base.connection.select_all("select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from journals inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and #{restcondchanges} order by journals.id desc) a group by issueId, created_on, prop_key, value order by created_on desc").each{|row| @changes << row}
 =begin
     select * from
     (
-      select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from `journals`
+      select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from journals
         inner join journal_details on (journals.id = journal_id)
         inner join issues on (issues.id = journalized_id)
         where journalized_type = 'Issue'
@@ -66,7 +66,7 @@ class AdburndownController < ApplicationController
           and (prop_key = 'estimated_hours' or prop_key = 'done_ratio')
           and #{restcondchanges}
         order by journals.id desc
-    ) a group by `issueId`, created_on, prop_key order by created_on desc
+    ) a group by issueId, created_on, prop_key order by created_on desc
 =end
     @changes = @changes.to_json
   end

```

Kind regards
Kamil

**Comment by robo-cbtn** [comment]
Worked like a charm! Thanks eximius313
