### ISSUE TITLE
Url adress problem

### ISSUE THREAD

**Issue by mziolek** [iRessources/AgileDwarf#7]
Redmine available on http://10.23.64.60/redmine/ but requests send to http://10.23.64.60/adtaskinl/tooltip
In firebug, I've got error "NetworkError: 404 Not Found - http://10.23.64.60/adtaskinl/tooltip"

On Tasks or Sprints pages don't work: tooltips, editing, new tasks etc.

OS: Ubuntu 12.04 LTS desktop
Redmine 1.3.2.stable (MySQL), ruby 1.8.7 

Regards
Martin

**Comment by markablov** [comment]
fixed by 7604224ee5
